# Generated by Django 6.0.3 on 2026-04-05 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='motivo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
