# Generated by Django 6.0.3 on 2026-04-05 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0002_alter_agendamento_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('AGENDADO', 'Agendado')], default='AGENDADO', max_length=20),
        ),
    ]
