# Generated by Django 6.0.3 on 2026-04-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0003_alter_agendamento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='tempo_espera',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
