# Generated by Django 6.0.3 on 2026-04-05 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0004_agendamento_tempo_espera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='motivo',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='tempo_espera',
        ),
    ]
