# Generated by Django 6.0.3 on 2026-04-03 23:47

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nome_social', models.CharField(blank=True, max_length=100, null=True)),
                ('nome_mae', models.CharField(max_length=100)),
                ('nome_pai', models.CharField(blank=True, max_length=100, null=True)),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$', 'CPF inválido! Use XXX.XXX.XXX-XX')])),
                ('data_nascimento', models.DateField()),
                ('sexo_biologico', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('I', 'Intersexo')], max_length=1)),
                ('identidade_genero', models.CharField(max_length=50)),
                ('orientacao_sexual', models.CharField(max_length=50)),
                ('nacionalidade', models.CharField(choices=[('BRASILEIRA', 'Brasileira'), ('ARGENTINA', 'Argentina'), ('BOLIVIANA', 'Boliviana'), ('CHILENA', 'Chilena'), ('COLOMBIANA', 'Colombiana'), ('PARAGUAIA', 'Paraguaia'), ('PERUANA', 'Peruana'), ('URUGUAIA', 'Uruguaia'), ('VENEZUELANA', 'Venezuelana'), ('OUTRA', 'Outra')], default='BRASILEIRA', max_length=20)),
                ('naturalidade', models.CharField(max_length=100)),
                ('raca_cor', models.CharField(choices=[('BRANCA', 'Branca'), ('PRETA', 'Preta'), ('PARDA', 'Parda'), ('AMARELA', 'Amarela'), ('INDIGENA', 'Indígena')], max_length=10)),
                ('estado_civil', models.CharField(choices=[('SOLTEIRO', 'Solteiro(a)'), ('CASADO', 'Casado(a)'), ('DIVORCIADO', 'Divorciado(a)'), ('VIUVO', 'Viúvo(a)'), ('UNIAO_ESTAVEL', 'União Estável')], max_length=20)),
                ('escolaridade', models.CharField(choices=[('SEM_INSTRUCAO', 'Sem instrução'), ('FUNDAMENTAL_INCOMPLETO', 'Fundamental incompleto'), ('FUNDAMENTAL_COMPLETO', 'Fundamental completo'), ('MEDIO_INCOMPLETO', 'Médio incompleto'), ('MEDIO_COMPLETO', 'Médio completo'), ('SUPERIOR_INCOMPLETO', 'Superior incompleto'), ('SUPERIOR_COMPLETO', 'Superior completo'), ('POS_GRADUACAO', 'Pós-graduação'), ('MESTRADO', 'Mestrado'), ('DOUTORADO', 'Doutorado')], max_length=30)),
                ('profissao', models.CharField(max_length=50)),
                ('rg', models.CharField(max_length=20)),
                ('orgao_emissor', models.CharField(max_length=10)),
                ('uf_rg', models.CharField(choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=2)),
                ('cep', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d{5}-\\d{3}$', 'CEP inválido! Use XXXXX-XXX')])),
                ('endereco', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=50, null=True)),
                ('bairro', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=50)),
                ('uf', models.CharField(choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=2)),
                ('zona', models.CharField(choices=[('URBANA', 'Urbana'), ('RURAL', 'Rural')], max_length=6)),
                ('telefone_fixo', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\(\\d{2}\\)\\s\\d{4}-\\d{4}$', 'Telefone inválido! Use (XX) XXXX-XXXX')])),
                ('celular', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\(\\d{2}\\)\\s\\d{5}-\\d{4}$', 'Celular inválido! Use (XX) XXXXX-XXXX')])),
                ('whatsapp', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cartao_sus', models.CharField(blank=True, max_length=18, null=True)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
