# Generated by Django 6.0.3 on 2026-04-06 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('triagem', '0002_triagem_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtendimentoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('prescricao', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('em_atendimento', 'Em atendimento'), ('finalizado', 'Finalizado')], default='em_atendimento', max_length=20)),
                ('data_atendimento', models.DateTimeField(auto_now_add=True)),
                ('triagem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='triagem.triagem')),
            ],
        ),
    ]
