# Generated by Django 6.0.3 on 2026-04-05 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agendamento', '0004_agendamento_tempo_espera'),
    ]

    operations = [
        migrations.CreateModel(
            name='Triagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressao_arterial', models.CharField(max_length=20)),
                ('temperatura', models.CharField(max_length=10)),
                ('batimentos_cardiacos', models.CharField(max_length=10)),
                ('sintomas', models.TextField()),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], max_length=20)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('agendamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='agendamento.agendamento')),
            ],
        ),
    ]
