# Generated by Django 6.0.3 on 2026-04-05 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agendamento', '0004_agendamento_tempo_espera'),
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Triagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressao', models.CharField(max_length=20)),
                ('temperatura', models.FloatField()),
                ('batimento_cardiaco', models.IntegerField()),
                ('saturacao', models.IntegerField()),
                ('queixa', models.TextField()),
                ('prioridade', models.CharField(choices=[('VERDE', 'Verde - Não urgente'), ('AMARELO', 'Amarelo - Pouco urgente'), ('VERMELHO', 'Vermelho - Emergência')], default='VERDE', max_length=10)),
                ('data_triagem', models.DateTimeField(auto_now_add=True)),
                ('agendamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='agendamento.agendamento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
            ],
        ),
    ]
