# Generated by Django 6.0.3 on 2026-04-06 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='triagem',
            name='status',
            field=models.CharField(choices=[('espera', 'Em espera'), ('atendimento', 'Em atendimento'), ('finalizado', 'Finalizado')], default='espera', max_length=20),
        ),
    ]
