# Generated by Django 6.0.3 on 2026-04-05 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
        ('triagem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='triagem',
            old_name='data',
            new_name='data_triagem',
        ),
        migrations.RenameField(
            model_name='triagem',
            old_name='pressao_arterial',
            new_name='pressao',
        ),
        migrations.RemoveField(
            model_name='triagem',
            name='agendamento',
        ),
        migrations.RemoveField(
            model_name='triagem',
            name='batimentos_cardiacos',
        ),
        migrations.RemoveField(
            model_name='triagem',
            name='prioridade',
        ),
        migrations.RemoveField(
            model_name='triagem',
            name='temperatura',
        ),
        migrations.AddField(
            model_name='triagem',
            name='classificacao',
            field=models.CharField(choices=[('vermelho', 'Emergência'), ('laranja', 'Muito urgente'), ('amarelo', 'Urgente'), ('verde', 'Pouco urgente'), ('azul', 'Não urgente')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='triagem',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente'),
            preserve_default=False,
        ),
    ]
