# Generated by Django 6.0.3 on 2026-04-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0003_alter_triagem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagem',
            name='status',
            field=models.CharField(choices=[('espera', 'Em espera'), ('atendimento', 'Em atendimento'), ('internacao', 'Internação'), ('medicacao', 'Medicação'), ('alta', 'Alta'), ('dispensado', 'Dispensado')], default='espera', max_length=20),
        ),
    ]
