# Generated by Django 6.0.3 on 2026-04-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0004_alter_triagem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagem',
            name='status',
            field=models.CharField(choices=[('espera', 'Em espera'), ('atendimento', 'Em atendimento'), ('internacao', 'Internação'), ('aguardando_medicacao', 'Aguardando Medicação'), ('medicado', 'Medicado'), ('alta', 'Alta'), ('dispensado', 'Dispensado')], default='espera', max_length=30),
        ),
    ]
