# Generated by Django 6.0.3 on 2026-04-19 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('triagem', '0004_alter_triagem_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(max_length=200)),
                ('dose', models.CharField(max_length=100)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_aplicacao', models.DateTimeField(auto_now_add=True)),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('triagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='triagem.triagem')),
            ],
        ),
    ]
